use_frameworks!

platform :ios, '14.1'

install! 'cocoapods', :deterministic_uuids => false

target 'KaMPKitiOS' do
    pod 'shared', :path => '../shared/'
    pod 'KMPNativeCoroutinesCombine', '~> 0.2'
    pod 'SwiftUIRefresh'
end
